scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: box
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_link
        min_x: -0.2140
        max_x: 0.2140
        min_y: -0.2140
        max_y: 0.2140
        min_z: -0.20
        max_z: 0.20